name: loading_more_list
description: A loading more list which supports ListView,GridView,WaterfallFlow and Slivers.
version: 7.0.1
repository: https://github.com/fluttercandies/loading_more_list

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  extended_list: ^3.0.0
  extended_list_library: ^3.0.0
  flutter:
    sdk: flutter
  loading_more_list_library: ^3.0.0
  waterfall_flow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
# dependency_overrides:
#   loading_more_list_library:
#     path: ../loading_more_list_library
flutter:
  uses-material-design: true
  assets:
    - assets/
